// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Generation is the predicate function for generation builders.
type Generation func(*sql.Selector)

// Resume is the predicate function for resume builders.
type Resume func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
