// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/user/resume-generator/backend/ent/generation"
	"github.com/user/resume-generator/backend/ent/resume"
)

// GenerationCreate is the builder for creating a Generation entity.
type GenerationCreate struct {
	config
	mutation *GenerationMutation
	hooks    []Hook
}

// SetJobDescription sets the "job_description" field.
func (_c *GenerationCreate) SetJobDescription(v string) *GenerationCreate {
	_c.mutation.SetJobDescription(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *GenerationCreate) SetStatus(v string) *GenerationCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *GenerationCreate) SetNillableStatus(v *string) *GenerationCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetResult sets the "result" field.
func (_c *GenerationCreate) SetResult(v string) *GenerationCreate {
	_c.mutation.SetResult(v)
	return _c
}

// SetNillableResult sets the "result" field if the given value is not nil.
func (_c *GenerationCreate) SetNillableResult(v *string) *GenerationCreate {
	if v != nil {
		_c.SetResult(*v)
	}
	return _c
}

// SetResumeID sets the "resume" edge to the Resume entity by ID.
func (_c *GenerationCreate) SetResumeID(id int) *GenerationCreate {
	_c.mutation.SetResumeID(id)
	return _c
}

// SetResume sets the "resume" edge to the Resume entity.
func (_c *GenerationCreate) SetResume(v *Resume) *GenerationCreate {
	return _c.SetResumeID(v.ID)
}

// Mutation returns the GenerationMutation object of the builder.
func (_c *GenerationCreate) Mutation() *GenerationMutation {
	return _c.mutation
}

// Save creates the Generation in the database.
func (_c *GenerationCreate) Save(ctx context.Context) (*Generation, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GenerationCreate) SaveX(ctx context.Context) *Generation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GenerationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GenerationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GenerationCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := generation.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GenerationCreate) check() error {
	if _, ok := _c.mutation.JobDescription(); !ok {
		return &ValidationError{Name: "job_description", err: errors.New(`ent: missing required field "Generation.job_description"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Generation.status"`)}
	}
	if len(_c.mutation.ResumeIDs()) == 0 {
		return &ValidationError{Name: "resume", err: errors.New(`ent: missing required edge "Generation.resume"`)}
	}
	return nil
}

func (_c *GenerationCreate) sqlSave(ctx context.Context) (*Generation, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GenerationCreate) createSpec() (*Generation, *sqlgraph.CreateSpec) {
	var (
		_node = &Generation{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(generation.Table, sqlgraph.NewFieldSpec(generation.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.JobDescription(); ok {
		_spec.SetField(generation.FieldJobDescription, field.TypeString, value)
		_node.JobDescription = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(generation.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Result(); ok {
		_spec.SetField(generation.FieldResult, field.TypeString, value)
		_node.Result = value
	}
	if nodes := _c.mutation.ResumeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   generation.ResumeTable,
			Columns: []string{generation.ResumeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resume.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.resume_generations = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// GenerationCreateBulk is the builder for creating many Generation entities in bulk.
type GenerationCreateBulk struct {
	config
	err      error
	builders []*GenerationCreate
}

// Save creates the Generation entities in the database.
func (_c *GenerationCreateBulk) Save(ctx context.Context) ([]*Generation, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Generation, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GenerationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GenerationCreateBulk) SaveX(ctx context.Context) []*Generation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GenerationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GenerationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
