// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/user/resume-generator/backend/ent/generation"
	"github.com/user/resume-generator/backend/ent/predicate"
	"github.com/user/resume-generator/backend/ent/resume"
)

// GenerationUpdate is the builder for updating Generation entities.
type GenerationUpdate struct {
	config
	hooks    []Hook
	mutation *GenerationMutation
}

// Where appends a list predicates to the GenerationUpdate builder.
func (_u *GenerationUpdate) Where(ps ...predicate.Generation) *GenerationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetJobDescription sets the "job_description" field.
func (_u *GenerationUpdate) SetJobDescription(v string) *GenerationUpdate {
	_u.mutation.SetJobDescription(v)
	return _u
}

// SetNillableJobDescription sets the "job_description" field if the given value is not nil.
func (_u *GenerationUpdate) SetNillableJobDescription(v *string) *GenerationUpdate {
	if v != nil {
		_u.SetJobDescription(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *GenerationUpdate) SetStatus(v string) *GenerationUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *GenerationUpdate) SetNillableStatus(v *string) *GenerationUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetResult sets the "result" field.
func (_u *GenerationUpdate) SetResult(v string) *GenerationUpdate {
	_u.mutation.SetResult(v)
	return _u
}

// SetNillableResult sets the "result" field if the given value is not nil.
func (_u *GenerationUpdate) SetNillableResult(v *string) *GenerationUpdate {
	if v != nil {
		_u.SetResult(*v)
	}
	return _u
}

// ClearResult clears the value of the "result" field.
func (_u *GenerationUpdate) ClearResult() *GenerationUpdate {
	_u.mutation.ClearResult()
	return _u
}

// SetResumeID sets the "resume" edge to the Resume entity by ID.
func (_u *GenerationUpdate) SetResumeID(id int) *GenerationUpdate {
	_u.mutation.SetResumeID(id)
	return _u
}

// SetResume sets the "resume" edge to the Resume entity.
func (_u *GenerationUpdate) SetResume(v *Resume) *GenerationUpdate {
	return _u.SetResumeID(v.ID)
}

// Mutation returns the GenerationMutation object of the builder.
func (_u *GenerationUpdate) Mutation() *GenerationMutation {
	return _u.mutation
}

// ClearResume clears the "resume" edge to the Resume entity.
func (_u *GenerationUpdate) ClearResume() *GenerationUpdate {
	_u.mutation.ClearResume()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GenerationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GenerationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GenerationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GenerationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GenerationUpdate) check() error {
	if _u.mutation.ResumeCleared() && len(_u.mutation.ResumeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Generation.resume"`)
	}
	return nil
}

func (_u *GenerationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(generation.Table, generation.Columns, sqlgraph.NewFieldSpec(generation.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.JobDescription(); ok {
		_spec.SetField(generation.FieldJobDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(generation.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Result(); ok {
		_spec.SetField(generation.FieldResult, field.TypeString, value)
	}
	if _u.mutation.ResultCleared() {
		_spec.ClearField(generation.FieldResult, field.TypeString)
	}
	if _u.mutation.ResumeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   generation.ResumeTable,
			Columns: []string{generation.ResumeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resume.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ResumeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   generation.ResumeTable,
			Columns: []string{generation.ResumeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resume.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{generation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GenerationUpdateOne is the builder for updating a single Generation entity.
type GenerationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GenerationMutation
}

// SetJobDescription sets the "job_description" field.
func (_u *GenerationUpdateOne) SetJobDescription(v string) *GenerationUpdateOne {
	_u.mutation.SetJobDescription(v)
	return _u
}

// SetNillableJobDescription sets the "job_description" field if the given value is not nil.
func (_u *GenerationUpdateOne) SetNillableJobDescription(v *string) *GenerationUpdateOne {
	if v != nil {
		_u.SetJobDescription(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *GenerationUpdateOne) SetStatus(v string) *GenerationUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *GenerationUpdateOne) SetNillableStatus(v *string) *GenerationUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetResult sets the "result" field.
func (_u *GenerationUpdateOne) SetResult(v string) *GenerationUpdateOne {
	_u.mutation.SetResult(v)
	return _u
}

// SetNillableResult sets the "result" field if the given value is not nil.
func (_u *GenerationUpdateOne) SetNillableResult(v *string) *GenerationUpdateOne {
	if v != nil {
		_u.SetResult(*v)
	}
	return _u
}

// ClearResult clears the value of the "result" field.
func (_u *GenerationUpdateOne) ClearResult() *GenerationUpdateOne {
	_u.mutation.ClearResult()
	return _u
}

// SetResumeID sets the "resume" edge to the Resume entity by ID.
func (_u *GenerationUpdateOne) SetResumeID(id int) *GenerationUpdateOne {
	_u.mutation.SetResumeID(id)
	return _u
}

// SetResume sets the "resume" edge to the Resume entity.
func (_u *GenerationUpdateOne) SetResume(v *Resume) *GenerationUpdateOne {
	return _u.SetResumeID(v.ID)
}

// Mutation returns the GenerationMutation object of the builder.
func (_u *GenerationUpdateOne) Mutation() *GenerationMutation {
	return _u.mutation
}

// ClearResume clears the "resume" edge to the Resume entity.
func (_u *GenerationUpdateOne) ClearResume() *GenerationUpdateOne {
	_u.mutation.ClearResume()
	return _u
}

// Where appends a list predicates to the GenerationUpdate builder.
func (_u *GenerationUpdateOne) Where(ps ...predicate.Generation) *GenerationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GenerationUpdateOne) Select(field string, fields ...string) *GenerationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Generation entity.
func (_u *GenerationUpdateOne) Save(ctx context.Context) (*Generation, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GenerationUpdateOne) SaveX(ctx context.Context) *Generation {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GenerationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GenerationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GenerationUpdateOne) check() error {
	if _u.mutation.ResumeCleared() && len(_u.mutation.ResumeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Generation.resume"`)
	}
	return nil
}

func (_u *GenerationUpdateOne) sqlSave(ctx context.Context) (_node *Generation, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(generation.Table, generation.Columns, sqlgraph.NewFieldSpec(generation.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Generation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, generation.FieldID)
		for _, f := range fields {
			if !generation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != generation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.JobDescription(); ok {
		_spec.SetField(generation.FieldJobDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(generation.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Result(); ok {
		_spec.SetField(generation.FieldResult, field.TypeString, value)
	}
	if _u.mutation.ResultCleared() {
		_spec.ClearField(generation.FieldResult, field.TypeString)
	}
	if _u.mutation.ResumeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   generation.ResumeTable,
			Columns: []string{generation.ResumeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resume.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ResumeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   generation.ResumeTable,
			Columns: []string{generation.ResumeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resume.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Generation{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{generation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
