// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/user/resume-generator/backend/ent/resume"
	"github.com/user/resume-generator/backend/ent/user"
)

// Resume is the model entity for the Resume schema.
type Resume struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Content holds the value of the "content" field.
	Content string `json:"content,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ResumeQuery when eager-loading is set.
	Edges        ResumeEdges `json:"edges"`
	user_resumes *int
	selectValues sql.SelectValues
}

// ResumeEdges holds the relations/edges for other nodes in the graph.
type ResumeEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Generations holds the value of the generations edge.
	Generations []*Generation `json:"generations,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ResumeEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// GenerationsOrErr returns the Generations value or an error if the edge
// was not loaded in eager-loading.
func (e ResumeEdges) GenerationsOrErr() ([]*Generation, error) {
	if e.loadedTypes[1] {
		return e.Generations, nil
	}
	return nil, &NotLoadedError{edge: "generations"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Resume) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case resume.FieldID:
			values[i] = new(sql.NullInt64)
		case resume.FieldTitle, resume.FieldContent, resume.FieldStatus:
			values[i] = new(sql.NullString)
		case resume.ForeignKeys[0]: // user_resumes
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Resume fields.
func (_m *Resume) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case resume.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case resume.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case resume.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				_m.Content = value.String
			}
		case resume.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case resume.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_resumes", value)
			} else if value.Valid {
				_m.user_resumes = new(int)
				*_m.user_resumes = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Resume.
// This includes values selected through modifiers, order, etc.
func (_m *Resume) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the Resume entity.
func (_m *Resume) QueryUser() *UserQuery {
	return NewResumeClient(_m.config).QueryUser(_m)
}

// QueryGenerations queries the "generations" edge of the Resume entity.
func (_m *Resume) QueryGenerations() *GenerationQuery {
	return NewResumeClient(_m.config).QueryGenerations(_m)
}

// Update returns a builder for updating this Resume.
// Note that you need to call Resume.Unwrap() before calling this method if this Resume
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Resume) Update() *ResumeUpdateOne {
	return NewResumeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Resume entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Resume) Unwrap() *Resume {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Resume is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Resume) String() string {
	var builder strings.Builder
	builder.WriteString("Resume(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("content=")
	builder.WriteString(_m.Content)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteByte(')')
	return builder.String()
}

// Resumes is a parsable slice of Resume.
type Resumes []*Resume
