// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/user/resume-generator/backend/ent/generation"
	"github.com/user/resume-generator/backend/ent/resume"
	"github.com/user/resume-generator/backend/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	generationFields := schema.Generation{}.Fields()
	_ = generationFields
	// generationDescStatus is the schema descriptor for status field.
	generationDescStatus := generationFields[1].Descriptor()
	// generation.DefaultStatus holds the default value on creation for the status field.
	generation.DefaultStatus = generationDescStatus.Default.(string)
	resumeFields := schema.Resume{}.Fields()
	_ = resumeFields
	// resumeDescContent is the schema descriptor for content field.
	resumeDescContent := resumeFields[1].Descriptor()
	// resume.DefaultContent holds the default value on creation for the content field.
	resume.DefaultContent = resumeDescContent.Default.(string)
	// resumeDescStatus is the schema descriptor for status field.
	resumeDescStatus := resumeFields[2].Descriptor()
	// resume.DefaultStatus holds the default value on creation for the status field.
	resume.DefaultStatus = resumeDescStatus.Default.(string)
}
