// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// GenerationsColumns holds the columns for the "generations" table.
	GenerationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "job_description", Type: field.TypeString},
		{Name: "status", Type: field.TypeString, Default: "pending"},
		{Name: "result", Type: field.TypeString, Nullable: true},
		{Name: "resume_generations", Type: field.TypeInt},
	}
	// GenerationsTable holds the schema information for the "generations" table.
	GenerationsTable = &schema.Table{
		Name:       "generations",
		Columns:    GenerationsColumns,
		PrimaryKey: []*schema.Column{GenerationsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "generations_resumes_generations",
				Columns:    []*schema.Column{GenerationsColumns[4]},
				RefColumns: []*schema.Column{ResumesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// ResumesColumns holds the columns for the "resumes" table.
	ResumesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString},
		{Name: "content", Type: field.TypeString, Default: "{}"},
		{Name: "status", Type: field.TypeString, Default: "draft"},
		{Name: "user_resumes", Type: field.TypeInt},
	}
	// ResumesTable holds the schema information for the "resumes" table.
	ResumesTable = &schema.Table{
		Name:       "resumes",
		Columns:    ResumesColumns,
		PrimaryKey: []*schema.Column{ResumesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "resumes_users_resumes",
				Columns:    []*schema.Column{ResumesColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "full_name", Type: field.TypeString},
		{Name: "password_hash", Type: field.TypeString},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		GenerationsTable,
		ResumesTable,
		UsersTable,
	}
)

func init() {
	GenerationsTable.ForeignKeys[0].RefTable = ResumesTable
	ResumesTable.ForeignKeys[0].RefTable = UsersTable
}
