// Code generated by ent, DO NOT EDIT.

package generation

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/user/resume-generator/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Generation {
	return predicate.Generation(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Generation {
	return predicate.Generation(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Generation {
	return predicate.Generation(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Generation {
	return predicate.Generation(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Generation {
	return predicate.Generation(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Generation {
	return predicate.Generation(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Generation {
	return predicate.Generation(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Generation {
	return predicate.Generation(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Generation {
	return predicate.Generation(sql.FieldLTE(FieldID, id))
}

// JobDescription applies equality check predicate on the "job_description" field. It's identical to JobDescriptionEQ.
func JobDescription(v string) predicate.Generation {
	return predicate.Generation(sql.FieldEQ(FieldJobDescription, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Generation {
	return predicate.Generation(sql.FieldEQ(FieldStatus, v))
}

// Result applies equality check predicate on the "result" field. It's identical to ResultEQ.
func Result(v string) predicate.Generation {
	return predicate.Generation(sql.FieldEQ(FieldResult, v))
}

// JobDescriptionEQ applies the EQ predicate on the "job_description" field.
func JobDescriptionEQ(v string) predicate.Generation {
	return predicate.Generation(sql.FieldEQ(FieldJobDescription, v))
}

// JobDescriptionNEQ applies the NEQ predicate on the "job_description" field.
func JobDescriptionNEQ(v string) predicate.Generation {
	return predicate.Generation(sql.FieldNEQ(FieldJobDescription, v))
}

// JobDescriptionIn applies the In predicate on the "job_description" field.
func JobDescriptionIn(vs ...string) predicate.Generation {
	return predicate.Generation(sql.FieldIn(FieldJobDescription, vs...))
}

// JobDescriptionNotIn applies the NotIn predicate on the "job_description" field.
func JobDescriptionNotIn(vs ...string) predicate.Generation {
	return predicate.Generation(sql.FieldNotIn(FieldJobDescription, vs...))
}

// JobDescriptionGT applies the GT predicate on the "job_description" field.
func JobDescriptionGT(v string) predicate.Generation {
	return predicate.Generation(sql.FieldGT(FieldJobDescription, v))
}

// JobDescriptionGTE applies the GTE predicate on the "job_description" field.
func JobDescriptionGTE(v string) predicate.Generation {
	return predicate.Generation(sql.FieldGTE(FieldJobDescription, v))
}

// JobDescriptionLT applies the LT predicate on the "job_description" field.
func JobDescriptionLT(v string) predicate.Generation {
	return predicate.Generation(sql.FieldLT(FieldJobDescription, v))
}

// JobDescriptionLTE applies the LTE predicate on the "job_description" field.
func JobDescriptionLTE(v string) predicate.Generation {
	return predicate.Generation(sql.FieldLTE(FieldJobDescription, v))
}

// JobDescriptionContains applies the Contains predicate on the "job_description" field.
func JobDescriptionContains(v string) predicate.Generation {
	return predicate.Generation(sql.FieldContains(FieldJobDescription, v))
}

// JobDescriptionHasPrefix applies the HasPrefix predicate on the "job_description" field.
func JobDescriptionHasPrefix(v string) predicate.Generation {
	return predicate.Generation(sql.FieldHasPrefix(FieldJobDescription, v))
}

// JobDescriptionHasSuffix applies the HasSuffix predicate on the "job_description" field.
func JobDescriptionHasSuffix(v string) predicate.Generation {
	return predicate.Generation(sql.FieldHasSuffix(FieldJobDescription, v))
}

// JobDescriptionEqualFold applies the EqualFold predicate on the "job_description" field.
func JobDescriptionEqualFold(v string) predicate.Generation {
	return predicate.Generation(sql.FieldEqualFold(FieldJobDescription, v))
}

// JobDescriptionContainsFold applies the ContainsFold predicate on the "job_description" field.
func JobDescriptionContainsFold(v string) predicate.Generation {
	return predicate.Generation(sql.FieldContainsFold(FieldJobDescription, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Generation {
	return predicate.Generation(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Generation {
	return predicate.Generation(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Generation {
	return predicate.Generation(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Generation {
	return predicate.Generation(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Generation {
	return predicate.Generation(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Generation {
	return predicate.Generation(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Generation {
	return predicate.Generation(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Generation {
	return predicate.Generation(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Generation {
	return predicate.Generation(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Generation {
	return predicate.Generation(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Generation {
	return predicate.Generation(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Generation {
	return predicate.Generation(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Generation {
	return predicate.Generation(sql.FieldContainsFold(FieldStatus, v))
}

// ResultEQ applies the EQ predicate on the "result" field.
func ResultEQ(v string) predicate.Generation {
	return predicate.Generation(sql.FieldEQ(FieldResult, v))
}

// ResultNEQ applies the NEQ predicate on the "result" field.
func ResultNEQ(v string) predicate.Generation {
	return predicate.Generation(sql.FieldNEQ(FieldResult, v))
}

// ResultIn applies the In predicate on the "result" field.
func ResultIn(vs ...string) predicate.Generation {
	return predicate.Generation(sql.FieldIn(FieldResult, vs...))
}

// ResultNotIn applies the NotIn predicate on the "result" field.
func ResultNotIn(vs ...string) predicate.Generation {
	return predicate.Generation(sql.FieldNotIn(FieldResult, vs...))
}

// ResultGT applies the GT predicate on the "result" field.
func ResultGT(v string) predicate.Generation {
	return predicate.Generation(sql.FieldGT(FieldResult, v))
}

// ResultGTE applies the GTE predicate on the "result" field.
func ResultGTE(v string) predicate.Generation {
	return predicate.Generation(sql.FieldGTE(FieldResult, v))
}

// ResultLT applies the LT predicate on the "result" field.
func ResultLT(v string) predicate.Generation {
	return predicate.Generation(sql.FieldLT(FieldResult, v))
}

// ResultLTE applies the LTE predicate on the "result" field.
func ResultLTE(v string) predicate.Generation {
	return predicate.Generation(sql.FieldLTE(FieldResult, v))
}

// ResultContains applies the Contains predicate on the "result" field.
func ResultContains(v string) predicate.Generation {
	return predicate.Generation(sql.FieldContains(FieldResult, v))
}

// ResultHasPrefix applies the HasPrefix predicate on the "result" field.
func ResultHasPrefix(v string) predicate.Generation {
	return predicate.Generation(sql.FieldHasPrefix(FieldResult, v))
}

// ResultHasSuffix applies the HasSuffix predicate on the "result" field.
func ResultHasSuffix(v string) predicate.Generation {
	return predicate.Generation(sql.FieldHasSuffix(FieldResult, v))
}

// ResultIsNil applies the IsNil predicate on the "result" field.
func ResultIsNil() predicate.Generation {
	return predicate.Generation(sql.FieldIsNull(FieldResult))
}

// ResultNotNil applies the NotNil predicate on the "result" field.
func ResultNotNil() predicate.Generation {
	return predicate.Generation(sql.FieldNotNull(FieldResult))
}

// ResultEqualFold applies the EqualFold predicate on the "result" field.
func ResultEqualFold(v string) predicate.Generation {
	return predicate.Generation(sql.FieldEqualFold(FieldResult, v))
}

// ResultContainsFold applies the ContainsFold predicate on the "result" field.
func ResultContainsFold(v string) predicate.Generation {
	return predicate.Generation(sql.FieldContainsFold(FieldResult, v))
}

// HasResume applies the HasEdge predicate on the "resume" edge.
func HasResume() predicate.Generation {
	return predicate.Generation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ResumeTable, ResumeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasResumeWith applies the HasEdge predicate on the "resume" edge with a given conditions (other predicates).
func HasResumeWith(preds ...predicate.Resume) predicate.Generation {
	return predicate.Generation(func(s *sql.Selector) {
		step := newResumeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Generation) predicate.Generation {
	return predicate.Generation(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Generation) predicate.Generation {
	return predicate.Generation(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Generation) predicate.Generation {
	return predicate.Generation(sql.NotPredicates(p))
}
